# Generated by Django 3.2.4 on 2021-10-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='hour_price',
        ),
    ]
