# Generated by Django 3.2.4 on 2021-10-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_hour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.DecimalField(decimal_places=0, default=80000, max_digits=6),
            preserve_default=False,
        ),
    ]
